language: java
jdk:
  - oraclejdk8
sudo: false
install: true

script:
  - ./gradlew war

after_success:
  - mkdir codedeploy
  - zip -r SimpleJavaProject.zip build/libs/test-1.0.0.war appspec.yml
  - mv SimpleJavaProject.zip codedeploy/
  - ls
  - pwd
  - cd codedeploy
  - ls
  - pwd




notifications:
  email:
    recipients:
      - instructor@csye6225.com