language: java
jdk:
  - oraclejdk8
sudo: false
install: true

script:
  - ./gradlew war

after_success:
  - cd ..
  - zip -r SimpleJavaProject.zip build/libs/test-1.0.0.war appspec.yml




notifications:
  email:
    recipients:
      - instructor@csye6225.com